library("epigrowthfit")
library("testthat")

test_that("`egf()` estimates `r` from data generated by exponential model", {
  f <- function(time, r, c0) {
    c0 * exp(r * time)
  }
  r <- log(2) / 20
  c0 <- 100
  nbdisp <- 10

  time <- 0:100
  mu <- diff(f(time, r = r, c0 = c0))

  set.seed(412575L)
  rhat <- replicate(25L, {
    x <- c(NA, rnbinom(length(mu), size = nbdisp, mu = mu))
    o <- egf(
      model = egf_model(curve = "exponential", family = "nbinom"),
      formula = x ~ time,
      endpoints = data.frame(start = min(time), end = max(time))
    )
    exp(o$best[[1L]])
  })
  expect_true(abs(mean(rhat) - r) / r < 0.05)
})

test_that("`egf()` estimates `r` from data generated by logistic model", {
  f <- function(time, r, tinfl, K) {
    K / (1 + exp(-r * (time - tinfl)))
  }
  r <- log(2) / 20
  c0 <- 100
  K <- 25000
  tinfl <- log(K / c0 - 1) / r
  nbdisp <- 10

  time <- 0:(ceiling(tinfl) + 1L)
  mu <- diff(f(time, r = r, tinfl = tinfl, K = K))

  set.seed(366465L)
  rhat <- replicate(25L, {
    x <- c(NA, rnbinom(length(mu), size = nbdisp, mu = mu))
    o <- egf(
      model = egf_model(curve = "logistic", family = "nbinom"),
      formula = x ~ time,
      endpoints = data.frame(start = min(time), end = max(time))
    )
    exp(o$best[[1L]])
  })
  expect_true(abs(mean(rhat) - r) / r < 0.05)
})

test_that("`egf()` estimates `r` from data generated by Richards model", {
  f <- function(time, r, tinfl, K, a) {
    K / (1 + a * exp(-r * a * (time - tinfl))^(1 / a))
  }
  r <- log(2) / 20
  c0 <- 100
  K <- 25000
  a <- 1.005
  tinfl <- (log((K / c0)^a - 1) - log(a)) / (r * a)
  nbdisp <- 10

  time <- 0:(ceiling(tinfl) + 1L)
  mu <- diff(f(time, r = r, tinfl = tinfl, K = K, a = a))

  set.seed(51520L)
  rhat <- replicate(25L, {
    x <- c(NA, rnbinom(length(mu), size = nbdisp, mu = mu))
    o <- egf(
      model = egf_model(curve = "richards", family = "nbinom"),
      formula = x ~ time,
      endpoints = data.frame(start = min(time), end = max(time))
    )
    exp(o$best[[1L]])
  })
  expect_true(abs(mean(rhat) - r) / r < 0.05)
})

test_that("`egf()` estimates `alpha` from data generated by subexponential model", {
  f <- function(time, alpha, c0, p) {
    (c0^(1 - p) + (1 - p) * alpha * time)^(1 / (1 - p))
  }
  alpha <- log(2) / 20
  c0 <- 100
  p <- 0.95
  nbdisp <- 10

  time <- 0:200
  mu <- diff(f(time, alpha = alpha, c0 = c0, p = p))

  set.seed(696180L)
  alphahat <- replicate(25L, {
    x <- c(NA, rnbinom(length(mu), size = nbdisp, mu = mu))
    o <- egf(
      model = egf_model(curve = "subexponential", family = "nbinom"),
      formula = x ~ time,
      endpoints = data.frame(start = min(time), end = max(time))
    )
    exp(o$best[[1L]])
  })
  expect_true(abs(mean(alphahat) - alpha) / alpha < 0.05)
})

test_that("`egf()` estimates `alpha` from data generated by Gompertz model", {
  f <- function(time, alpha, c0, K) {
    K * (c0 / K)^(exp(-alpha * time))
  }
  alpha <- log(2) / 20
  c0 <- 100
  K <- 25000
  nbdisp <- 10

  time <- 0:200
  mu <- diff(f(time, alpha = alpha, c0 = c0, K = K))

  set.seed(720748L)
  alphahat <- replicate(25L, {
    x <- c(NA, rnbinom(length(mu), size = nbdisp, mu = mu))
    o <- egf(
      model = egf_model(curve = "gompertz", family = "nbinom"),
      formula = x ~ time,
      endpoints = data.frame(start = min(time), end = max(time))
    )
    exp(o$best[[1L]])
  })
  expect_true(abs(mean(alphahat) - alpha) / alpha < 0.05)
})
